/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as TopologiesRouteImport } from './routes/topologies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsIdRouteImport } from './routes/simulations.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologiesRoute = TopologiesRouteImport.update({
  id: '/topologies',
  path: '/topologies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsIdRoute = SimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topologies': typeof TopologiesRoute
  '/workers': typeof WorkersRoute
  '/simulations/$id': typeof SimulationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topologies': typeof TopologiesRoute
  '/workers': typeof WorkersRoute
  '/simulations/$id': typeof SimulationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/topologies': typeof TopologiesRoute
  '/workers': typeof WorkersRoute
  '/simulations/$id': typeof SimulationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topologies' | '/workers' | '/simulations/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topologies' | '/workers' | '/simulations/$id'
  id: '__root__' | '/' | '/topologies' | '/workers' | '/simulations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopologiesRoute: typeof TopologiesRoute
  WorkersRoute: typeof WorkersRoute
  SimulationsIdRoute: typeof SimulationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topologies': {
      id: '/topologies'
      path: '/topologies'
      fullPath: '/topologies'
      preLoaderRoute: typeof TopologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$id': {
      id: '/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/simulations/$id'
      preLoaderRoute: typeof SimulationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopologiesRoute: TopologiesRoute,
  WorkersRoute: WorkersRoute,
  SimulationsIdRoute: SimulationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
